# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('cvd_portal', '0007_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='doctor',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='cvd_portal.Device'),
        ),
        migrations.AddField(
            model_name='patient',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='cvd_portal.Device'),
        ),
    ]
