# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0009_remove_device_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
