# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 11:13
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0010_device_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte', models.TextField()),
                ('time_stamp', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cvd_portal.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='time_stamp',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
    ]
