# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0011_auto_20171230_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.IntegerField(default=0),
        ),
    ]
