# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0012_auto_20180221_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('user_type', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
