# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvd_portal', '0013_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user_id',
            new_name='user_type_id',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
