# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 09:01
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0014_auto_20180225_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_stamp', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_d', to='cvd_portal.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_p', to='cvd_portal.Patient')),
            ],
        ),
    ]
