# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0015_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvd_portal.Doctor'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvd_portal.Patient'),
        ),
    ]
